### ISSUE TITLE
error: relation "videos" does not exist

### ISSUE THREAD

**Issue by ozbillwang** [all-in-aigc/sorafm#1]
got the error when deploy to vercel

```
error: relation "videos" does not exist
```

![image](https://github.com/all-in-aigc/sorafm/assets/8954908/571d5c8d-bbbe-4ca8-a6d3-512ce5d2c217)

duplicated the issue when run locally

![image](https://github.com/all-in-aigc/sorafm/assets/8954908/62ad6305-d9cc-4285-baca-666764f3fffb)

![image](https://github.com/all-in-aigc/sorafm/assets/8954908/8cf815f4-c542-4308-bfb4-1d738b153c57)

**Comment by ozbillwang** [comment]
ok, fixed with this command

```
psql "postgres://USER:PASSWORD@HOST/DB" -f data/install.sql
```

**Comment by joostshao** [comment]
suck

**Comment by Bloomingg** [comment]
I encountered the same problem, can you tell me how to solve it? I didn't find where to enter the instructions when deploying on vercel

**Comment by ozbillwang** [comment]
> I encountered the same problem, can you tell me how to solve it? I didn't find where to enter the instructions when deploying on vercel

In the readme, 

![image](https://github.com/all-in-aigc/sorafm/assets/8954908/baf1a8f1-d83d-449f-b5a7-80e5a96261fa)

After create the postgresql database, we need Initialize the database. The sql file is in the source code at [data/install.sql](https://github.com/all-in-aigc/sorafm/blob/main/data/install.sql) 

if you familar the `psql` command, the simpliest way is 

    psql "postgres://USER:PASSWORD@HOST/DB" -f data/install.sql

the part of "postgres://USER:PASSWORD@HOST/DB" is the psql connection string when you created the postgresql. 

If you don't have the psql command, you need install it first, please refer Postgresql official document for help.
