### ISSUE TITLE
Why can't I use the live demonstration demo?

### ISSUE THREAD

**Issue by psksiu** [all-in-aigc/sorafm#2]
Why can't I use the live demonstration demo?

**Comment by wangwwwwwwv** [comment]
it‘s not working too

**Comment by joostshao** [comment]
suck

**Comment by FavioVazquez** [comment]
How can we create "antistars" for a project, this is BS

**Comment by idoubi** [comment]
This project is a template for AI Video generating, it's not really work with your prompt until Sora API is available. All the videos show on Sora.FM are generated by OpenAI.
