### ISSUE TITLE
Can it work? The response is

### ISSUE THREAD

**Issue by scj725** [all-in-aigc/sorafm#3]
{
  "code": -1,
  "message": "gen video failed"
}

**Comment by joostshao** [comment]
suck

**Comment by idoubi** [comment]
This project is a template for AI Video generating, it's not really work with your prompt until Sora API is available. All the videos show on Sora.FM are generated by OpenAI.

Try it again when you got response like "gen video failed"

**Comment by PlayerYK** [comment]
Perhaps it would be better to provide some demonstration videos and include them in the SQL statement for creating the table. This way, it can run just like your demo site.
