### ISSUE TITLE
请问一下，这两个地方怎么填写

### ISSUE THREAD

**Issue by LyuPY123** [all-in-aigc/sorafm#4]
![QQ截图20240224230207](https://github.com/all-in-aigc/sorafm/assets/160851101/ccd4af92-e031-4d44-b65d-f38b27daddbd)

**Comment by tiwentichat** [comment]
下面手动部署那儿有这两行内容。我是用的supabase，第二行直接黏贴，第一行要在后台那儿看

**Comment by idoubi** [comment]
第一个填你的 postgres 连接地址，第二个填你的网站部署地址。
