### ISSUE TITLE
Unusual Implementation of Internationalization in Next.js Project

### ISSUE THREAD

**Issue by tianlelyd** [all-in-aigc/sorafm#8]
I noticed that in the project's package.json dependencies, the next-intl package is included. However, upon further inspection of the internationalization implementation in the project, it appears that the functionality is custom-coded and does not make use of the next-intl package at all.

This discrepancy raises questions about the necessity of including the next-intl package in the dependencies if it is not being utilized for internationalization. It would be beneficial to clarify the reasoning behind this implementation choice and ensure that the project's dependencies are aligned with the actual implementation.

I would appreciate it if the project author or maintainers could provide insights into the decision-making process regarding the internationalization strategy in the project.

**Comment by idoubi** [comment]
removed
